/*
 * This file is generated by jOOQ.
 */
package redcloud.dao.schema;


import javax.annotation.Generated;

import redcloud.dao.schema.tables.Directory;
import redcloud.dao.schema.tables.User;
import redcloud.dao.schema.tables.UserPrivilege;


/**
 * Convenience access to all tables in redcloud
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>redcloud.directory</code>.
     */
    public static final Directory DIRECTORY = redcloud.dao.schema.tables.Directory.DIRECTORY;

    /**
     * The table <code>redcloud.user</code>.
     */
    public static final User USER = redcloud.dao.schema.tables.User.USER;

    /**
     * The table <code>redcloud.user_privilege</code>.
     */
    public static final UserPrivilege USER_PRIVILEGE = redcloud.dao.schema.tables.UserPrivilege.USER_PRIVILEGE;
}
